### ISSUE TITLE
ReplyRepository

### ISSUE THREAD

**Issue by chansooo** [GongGanGam/GongGanGam-iOS#11]
# Description
> 받은 답장에 관한 데이터를 관리하는 repository

# TODO
- [ ] 받은 답장 fetch
- [ ] 받은 답장 remove
- [ ] 다른 사람의 일기에 답장 post
