### ISSUE TITLE
GongGanGam-UI.framework

### ISSUE THREAD

**Issue by yy0867** [GongGanGam/GongGanGam-iOS#57]
# Description
> description

# TODO
- [x] `TitledView` 구현
  - [x] `TitledTextField`, `TitledDatePicker`, `TitledSegmentedControl` 구현

    ![image](https://user-images.githubusercontent.com/27603734/214458570-c488ab92-fd6a-4ae6-88f6-08a70218804c.png)

- [x] `AlertBuilder` 구현

- [ ] Keyboard Follow 로직 구현

- [x] `BottomButton` 구현

  ![image](https://user-images.githubusercontent.com/27603734/214464922-249f4769-dffc-459d-a63c-f6552b68a0dc.png)

- [x] `CapsuleButton` 구현

  ![image](https://user-images.githubusercontent.com/27603734/214466104-f8924547-ddff-41de-a837-6b24ecfee2ee.png)

  ![image](https://user-images.githubusercontent.com/27603734/214466167-92658dbf-ae4e-4d5d-b3b8-a4dc2254afd0.png)

- [x] `CheckBox` 구현

  ![image](https://user-images.githubusercontent.com/27603734/214466226-4a89841e-2c6a-4a62-9027-6b730a8216ce.png)

- [x] `SelectEmotionCollectionView` 구현

  ![image](https://user-images.githubusercontent.com/27603734/214466273-1b9c5d50-943e-4ff3-8731-44e42bfe8be0.png)

- [ ] `LoadableImageView` 구현
  - [x] `ProfileImageView` 구현

- [ ] `ReceivedContentCell` 구현
  - [ ] 받은 답장 + 받은 일기 Cell

- [ ] `ChatListCell` 구현
- [ ] `ChatCell` 구현

- [ ] `TabPager` 구현

- [ ] MyPage의 공통된 Cell 구현

**Comment by yy0867** [comment]
`TitledTextField`의 Notification Observing 로직 변경하기
