### ISSUE TITLE
Coredata 모듈 구현

### ISSUE THREAD

**Issue by yy0867** [GongGanGam/GongGanGam-iOS#6]
# Description
> CoreData 모듈 구현

# TODO
- [x] insert(저장)
- [x] 특정 Entity의 모든 데이터 Fetch
- [x] 특정 Entity의 id로 단일 데이터 Fetch
- [x] 특정 Entity의 id로 단일 데이터 Delete
- [x] 특정 Entity의 id로 데이터 Update
